Setup react
Thinus01/math_magicians pull request #1
Opened 2023-01-23 13:47 UTC by Thinus01

The application should run in the browser without errors

2023-01-23 16:05 UTC, Lucas-Masaba requested changes
# Hello @Thinus01 👋 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ⚠️ 
- [ ] Please customise your README to suit your project. It should include all headers from the default [README template](https://github.com/microverseinc/readme-template#future-features). Do not leave any default or invalid information. It should be professional.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏 💻 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Lucas-Masaba in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-01-23 16:05 UTC, Lucas-Masaba commented on README.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p>
- [ ] Please include all headers to your README with the exception of FAQ which is optional. You are missing the future features header. Refer to the [default template](https://github.com/microverseinc/readme-template#future-features) to see this.

2023-01-23 16:05 UTC, Lucas-Masaba commented on README.md
> +    <li><a href="https://expressjs.com/">Express.js</a></li>
- [ ] Please remove express.js from your README because you have not used it for this project

2023-01-24 08:17 UTC, Olamarx requested changes
Hi @Thinus01,

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media4.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif"/>

## Highlights
- Linters passed ✔️
- CRA ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-24 08:17 UTC, Olamarx commented on README.md
> +> VS Editor, Github web pages, HTML, CSS and Java.
- [ ] You did not use java for this project so I will advise you to edit the whole sections so that it would fit your project.

2023-01-24 08:17 UTC, Olamarx commented on README.md
> +> Describe between 1-3 key features of the application.
- [ ] Kindly make a proper description here and not leave the demo content.

2023-01-24 08:17 UTC, Olamarx commented on README.md
> +> Describe how a new developer could make use of your project.
- [ ] Same here

2023-01-24 08:17 UTC, Olamarx commented on README.md
> +**``npm start``**
- [ ] Kindly explain this process to your visitors too by adding the appropriate info.

2023-01-24 09:55 UTC, TedLivist approved these changes
## STATUS: APPROVED ✔️ ✔️

Hi @Thinus01,

✔️ Good documentation

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-24 09:55 UTC, TedLivist approved these changes
## STATUS: APPROVED ✔️ ✔️

Hi @Thinus01,

✔️ Good documentation

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-25 09:24 UTC, merged